name: Security Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '19 13 * * 2'

jobs:
  security-checks:
    uses: joshjohanning-org/reusable-workflows/.github/workflows/security-checks.yml@security-checks
    with:
      runs-on: ubuntu-latest
    secrets: inherit
